// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server.proto
// Protobuf C++ Version: 4.26.0-dev

#include "server.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Raft {

inline constexpr RequestVote_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : term_{::uint64_t{0u}},
        votegranted_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestVote_Response::RequestVote_Response(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestVote_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestVote_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestVote_ResponseDefaultTypeInternal() {}
  union {
    RequestVote_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestVote_ResponseDefaultTypeInternal _RequestVote_Response_default_instance_;

inline constexpr RequestVote_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : term_{::uint64_t{0u}},
        candidateid_{::uint64_t{0u}},
        lastlogindex_{::uint64_t{0u}},
        lastlogterm_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestVote_Request::RequestVote_Request(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestVote_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestVote_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestVote_RequestDefaultTypeInternal() {}
  union {
    RequestVote_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestVote_RequestDefaultTypeInternal _RequestVote_Request_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR RequestVote::RequestVote(::_pbi::ConstantInitialized) {}
struct RequestVoteDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestVoteDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestVoteDefaultTypeInternal() {}
  union {
    RequestVote _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestVoteDefaultTypeInternal _RequestVote_default_instance_;

inline constexpr Entry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : cmd_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Entry::Entry(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct EntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EntryDefaultTypeInternal() {}
  union {
    Entry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EntryDefaultTypeInternal _Entry_default_instance_;

inline constexpr AppendEntries_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : term_{::uint64_t{0u}},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AppendEntries_Response::AppendEntries_Response(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AppendEntries_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppendEntries_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppendEntries_ResponseDefaultTypeInternal() {}
  union {
    AppendEntries_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppendEntries_ResponseDefaultTypeInternal _AppendEntries_Response_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR AppendEntries::AppendEntries(::_pbi::ConstantInitialized) {}
struct AppendEntriesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppendEntriesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppendEntriesDefaultTypeInternal() {}
  union {
    AppendEntries _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppendEntriesDefaultTypeInternal _AppendEntries_default_instance_;

inline constexpr AppendEntries_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : entries_{},
        term_{::uint64_t{0u}},
        leaderid_{::uint64_t{0u}},
        prevlogindex_{::uint64_t{0u}},
        prevlogterm_{::uint64_t{0u}},
        leadercommit_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AppendEntries_Request::AppendEntries_Request(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AppendEntries_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AppendEntries_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AppendEntries_RequestDefaultTypeInternal() {}
  union {
    AppendEntries_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AppendEntries_RequestDefaultTypeInternal _AppendEntries_Request_default_instance_;
}  // namespace Raft
static ::_pb::Metadata file_level_metadata_server_2eproto[7];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_server_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_server_2eproto = nullptr;
const ::uint32_t
    TableStruct_server_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::Entry, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Raft::Entry, _impl_.cmd_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.term_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.leaderid_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.prevlogindex_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.prevlogterm_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.entries_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Request, _impl_.leadercommit_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Response, _impl_.term_),
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries_Response, _impl_.success_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::AppendEntries, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Request, _impl_.term_),
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Request, _impl_.candidateid_),
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Request, _impl_.lastlogindex_),
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Request, _impl_.lastlogterm_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Response, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Response, _impl_.term_),
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote_Response, _impl_.votegranted_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Raft::RequestVote, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Raft::Entry)},
        {9, -1, -1, sizeof(::Raft::AppendEntries_Request)},
        {23, -1, -1, sizeof(::Raft::AppendEntries_Response)},
        {33, -1, -1, sizeof(::Raft::AppendEntries)},
        {41, -1, -1, sizeof(::Raft::RequestVote_Request)},
        {53, -1, -1, sizeof(::Raft::RequestVote_Response)},
        {63, -1, -1, sizeof(::Raft::RequestVote)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Raft::_Entry_default_instance_._instance,
    &::Raft::_AppendEntries_Request_default_instance_._instance,
    &::Raft::_AppendEntries_Response_default_instance_._instance,
    &::Raft::_AppendEntries_default_instance_._instance,
    &::Raft::_RequestVote_Request_default_instance_._instance,
    &::Raft::_RequestVote_Response_default_instance_._instance,
    &::Raft::_RequestVote_default_instance_._instance,
};
const char descriptor_table_protodef_server_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014server.proto\022\004Raft\"\024\n\005Entry\022\013\n\003cmd\030\001 \001"
    "(\014\"\305\001\n\rAppendEntries\032\210\001\n\007Request\022\014\n\004term"
    "\030\001 \001(\004\022\020\n\010leaderId\030\002 \001(\004\022\024\n\014prevLogIndex"
    "\030\003 \001(\004\022\023\n\013prevLogTerm\030\004 \001(\004\022\034\n\007entries\030\005"
    " \003(\0132\013.Raft.Entry\022\024\n\014leaderCommit\030\006 \001(\004\032"
    ")\n\010Response\022\014\n\004term\030\001 \001(\004\022\017\n\007success\030\002 \001"
    "(\010\"\225\001\n\013RequestVote\032W\n\007Request\022\014\n\004term\030\001 "
    "\001(\004\022\023\n\013candidateId\030\002 \001(\004\022\024\n\014lastLogIndex"
    "\030\003 \001(\004\022\023\n\013lastLogTerm\030\004 \001(\004\032-\n\010Response\022"
    "\014\n\004term\030\001 \001(\004\022\023\n\013voteGranted\030\002 \001(\010b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_server_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_server_2eproto = {
    false,
    false,
    402,
    descriptor_table_protodef_server_2eproto,
    "server.proto",
    &descriptor_table_server_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_server_2eproto::offsets,
    file_level_metadata_server_2eproto,
    file_level_enum_descriptors_server_2eproto,
    file_level_service_descriptors_server_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_server_2eproto_getter() {
  return &descriptor_table_server_2eproto;
}
namespace Raft {
// ===================================================================

class Entry::_Internal {
 public:
};

Entry::Entry(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Raft.Entry)
}
inline PROTOBUF_NDEBUG_INLINE Entry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : cmd_(arena, from.cmd_),
        _cached_size_{0} {}

Entry::Entry(
    ::google::protobuf::Arena* arena,
    const Entry& from)
    : ::google::protobuf::Message(arena) {
  Entry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Raft.Entry)
}
inline PROTOBUF_NDEBUG_INLINE Entry::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : cmd_(arena),
        _cached_size_{0} {}

inline void Entry::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Entry::~Entry() {
  // @@protoc_insertion_point(destructor:Raft.Entry)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Entry::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.cmd_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Entry::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Entry, _impl_._cached_size_),
              false,
          },
          &Entry::MergeImpl,
          &Entry::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Entry::Clear() {
// @@protoc_insertion_point(message_clear_start:Raft.Entry)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.cmd_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Entry::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> Entry::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Entry_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Raft::Entry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes cmd = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Entry, _impl_.cmd_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes cmd = 1;
    {PROTOBUF_FIELD_OFFSET(Entry, _impl_.cmd_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* Entry::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Raft.Entry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes cmd = 1;
  if (!this->_internal_cmd().empty()) {
    const std::string& _s = this->_internal_cmd();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Raft.Entry)
  return target;
}

::size_t Entry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Raft.Entry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes cmd = 1;
  if (!this->_internal_cmd().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_cmd());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Entry::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Entry*>(&to_msg);
  auto& from = static_cast<const Entry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Raft.Entry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_cmd().empty()) {
    _this->_internal_set_cmd(from._internal_cmd());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Entry::CopyFrom(const Entry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Raft.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Entry::IsInitialized() const {
  return true;
}

void Entry::InternalSwap(Entry* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cmd_, &other->_impl_.cmd_, arena);
}

::google::protobuf::Metadata Entry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[0]);
}
// ===================================================================

class AppendEntries_Request::_Internal {
 public:
};

AppendEntries_Request::AppendEntries_Request(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Raft.AppendEntries.Request)
}
inline PROTOBUF_NDEBUG_INLINE AppendEntries_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : entries_{visibility, arena, from.entries_},
        _cached_size_{0} {}

AppendEntries_Request::AppendEntries_Request(
    ::google::protobuf::Arena* arena,
    const AppendEntries_Request& from)
    : ::google::protobuf::Message(arena) {
  AppendEntries_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, term_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, term_),
           offsetof(Impl_, leadercommit_) -
               offsetof(Impl_, term_) +
               sizeof(Impl_::leadercommit_));

  // @@protoc_insertion_point(copy_constructor:Raft.AppendEntries.Request)
}
inline PROTOBUF_NDEBUG_INLINE AppendEntries_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : entries_{visibility, arena},
        _cached_size_{0} {}

inline void AppendEntries_Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, term_),
           0,
           offsetof(Impl_, leadercommit_) -
               offsetof(Impl_, term_) +
               sizeof(Impl_::leadercommit_));
}
AppendEntries_Request::~AppendEntries_Request() {
  // @@protoc_insertion_point(destructor:Raft.AppendEntries.Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AppendEntries_Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AppendEntries_Request::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_._cached_size_),
              false,
          },
          &AppendEntries_Request::MergeImpl,
          &AppendEntries_Request::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AppendEntries_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:Raft.AppendEntries.Request)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.entries_.Clear();
  ::memset(&_impl_.term_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.leadercommit_) -
      reinterpret_cast<char*>(&_impl_.term_)) + sizeof(_impl_.leadercommit_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AppendEntries_Request::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 0, 2> AppendEntries_Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AppendEntries_Request_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Raft::AppendEntries_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 term = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Request, _impl_.term_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.term_)}},
    // uint64 leaderId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Request, _impl_.leaderid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.leaderid_)}},
    // uint64 prevLogIndex = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Request, _impl_.prevlogindex_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.prevlogindex_)}},
    // uint64 prevLogTerm = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Request, _impl_.prevlogterm_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.prevlogterm_)}},
    // repeated .Raft.Entry entries = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.entries_)}},
    // uint64 leaderCommit = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Request, _impl_.leadercommit_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.leadercommit_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 term = 1;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.term_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 leaderId = 2;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.leaderid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 prevLogIndex = 3;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.prevlogindex_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 prevLogTerm = 4;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.prevlogterm_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // repeated .Raft.Entry entries = 5;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.entries_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint64 leaderCommit = 6;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.leadercommit_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Raft::Entry>()},
  }}, {{
  }},
};

::uint8_t* AppendEntries_Request::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Raft.AppendEntries.Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_term(), target);
  }

  // uint64 leaderId = 2;
  if (this->_internal_leaderid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_leaderid(), target);
  }

  // uint64 prevLogIndex = 3;
  if (this->_internal_prevlogindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_prevlogindex(), target);
  }

  // uint64 prevLogTerm = 4;
  if (this->_internal_prevlogterm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_prevlogterm(), target);
  }

  // repeated .Raft.Entry entries = 5;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_entries_size());
       i < n; i++) {
    const auto& repfield = this->_internal_entries().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            5, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // uint64 leaderCommit = 6;
  if (this->_internal_leadercommit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        6, this->_internal_leadercommit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Raft.AppendEntries.Request)
  return target;
}

::size_t AppendEntries_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Raft.AppendEntries.Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Raft.Entry entries = 5;
  total_size += 1UL * this->_internal_entries_size();
  for (const auto& msg : this->_internal_entries()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_term());
  }

  // uint64 leaderId = 2;
  if (this->_internal_leaderid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_leaderid());
  }

  // uint64 prevLogIndex = 3;
  if (this->_internal_prevlogindex() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_prevlogindex());
  }

  // uint64 prevLogTerm = 4;
  if (this->_internal_prevlogterm() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_prevlogterm());
  }

  // uint64 leaderCommit = 6;
  if (this->_internal_leadercommit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_leadercommit());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AppendEntries_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AppendEntries_Request*>(&to_msg);
  auto& from = static_cast<const AppendEntries_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Raft.AppendEntries.Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_entries()->MergeFrom(
      from._internal_entries());
  if (from._internal_term() != 0) {
    _this->_impl_.term_ = from._impl_.term_;
  }
  if (from._internal_leaderid() != 0) {
    _this->_impl_.leaderid_ = from._impl_.leaderid_;
  }
  if (from._internal_prevlogindex() != 0) {
    _this->_impl_.prevlogindex_ = from._impl_.prevlogindex_;
  }
  if (from._internal_prevlogterm() != 0) {
    _this->_impl_.prevlogterm_ = from._impl_.prevlogterm_;
  }
  if (from._internal_leadercommit() != 0) {
    _this->_impl_.leadercommit_ = from._impl_.leadercommit_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AppendEntries_Request::CopyFrom(const AppendEntries_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Raft.AppendEntries.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AppendEntries_Request::IsInitialized() const {
  return true;
}

void AppendEntries_Request::InternalSwap(AppendEntries_Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.entries_.InternalSwap(&other->_impl_.entries_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.leadercommit_)
      + sizeof(AppendEntries_Request::_impl_.leadercommit_)
      - PROTOBUF_FIELD_OFFSET(AppendEntries_Request, _impl_.term_)>(
          reinterpret_cast<char*>(&_impl_.term_),
          reinterpret_cast<char*>(&other->_impl_.term_));
}

::google::protobuf::Metadata AppendEntries_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[1]);
}
// ===================================================================

class AppendEntries_Response::_Internal {
 public:
};

AppendEntries_Response::AppendEntries_Response(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Raft.AppendEntries.Response)
}
AppendEntries_Response::AppendEntries_Response(
    ::google::protobuf::Arena* arena, const AppendEntries_Response& from)
    : AppendEntries_Response(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AppendEntries_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AppendEntries_Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, term_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, term_) +
               sizeof(Impl_::success_));
}
AppendEntries_Response::~AppendEntries_Response() {
  // @@protoc_insertion_point(destructor:Raft.AppendEntries.Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AppendEntries_Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AppendEntries_Response::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_._cached_size_),
              false,
          },
          &AppendEntries_Response::MergeImpl,
          &AppendEntries_Response::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void AppendEntries_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:Raft.AppendEntries.Response)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.term_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.term_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AppendEntries_Response::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> AppendEntries_Response::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AppendEntries_Response_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Raft::AppendEntries_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(AppendEntries_Response, _impl_.success_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.success_)}},
    // uint64 term = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AppendEntries_Response, _impl_.term_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.term_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 term = 1;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.term_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bool success = 2;
    {PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* AppendEntries_Response::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Raft.AppendEntries.Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_term(), target);
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_success(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Raft.AppendEntries.Response)
  return target;
}

::size_t AppendEntries_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Raft.AppendEntries.Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_term());
  }

  // bool success = 2;
  if (this->_internal_success() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AppendEntries_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AppendEntries_Response*>(&to_msg);
  auto& from = static_cast<const AppendEntries_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Raft.AppendEntries.Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_term() != 0) {
    _this->_impl_.term_ = from._impl_.term_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AppendEntries_Response::CopyFrom(const AppendEntries_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Raft.AppendEntries.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AppendEntries_Response::IsInitialized() const {
  return true;
}

void AppendEntries_Response::InternalSwap(AppendEntries_Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.success_)
      + sizeof(AppendEntries_Response::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(AppendEntries_Response, _impl_.term_)>(
          reinterpret_cast<char*>(&_impl_.term_),
          reinterpret_cast<char*>(&other->_impl_.term_));
}

::google::protobuf::Metadata AppendEntries_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[2]);
}
// ===================================================================

class AppendEntries::_Internal {
 public:
};

AppendEntries::AppendEntries(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:Raft.AppendEntries)
}
AppendEntries::AppendEntries(
    ::google::protobuf::Arena* arena,
    const AppendEntries& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  AppendEntries* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Raft.AppendEntries)
}









::google::protobuf::Metadata AppendEntries::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[3]);
}
// ===================================================================

class RequestVote_Request::_Internal {
 public:
};

RequestVote_Request::RequestVote_Request(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Raft.RequestVote.Request)
}
RequestVote_Request::RequestVote_Request(
    ::google::protobuf::Arena* arena, const RequestVote_Request& from)
    : RequestVote_Request(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RequestVote_Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RequestVote_Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, term_),
           0,
           offsetof(Impl_, lastlogterm_) -
               offsetof(Impl_, term_) +
               sizeof(Impl_::lastlogterm_));
}
RequestVote_Request::~RequestVote_Request() {
  // @@protoc_insertion_point(destructor:Raft.RequestVote.Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestVote_Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestVote_Request::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_._cached_size_),
              false,
          },
          &RequestVote_Request::MergeImpl,
          &RequestVote_Request::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void RequestVote_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:Raft.RequestVote.Request)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.term_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.lastlogterm_) -
      reinterpret_cast<char*>(&_impl_.term_)) + sizeof(_impl_.lastlogterm_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestVote_Request::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2> RequestVote_Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestVote_Request_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Raft::RequestVote_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 lastLogTerm = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestVote_Request, _impl_.lastlogterm_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.lastlogterm_)}},
    // uint64 term = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestVote_Request, _impl_.term_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.term_)}},
    // uint64 candidateId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestVote_Request, _impl_.candidateid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.candidateid_)}},
    // uint64 lastLogIndex = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestVote_Request, _impl_.lastlogindex_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.lastlogindex_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 term = 1;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.term_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 candidateId = 2;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.candidateid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 lastLogIndex = 3;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.lastlogindex_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint64 lastLogTerm = 4;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.lastlogterm_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RequestVote_Request::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Raft.RequestVote.Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_term(), target);
  }

  // uint64 candidateId = 2;
  if (this->_internal_candidateid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_candidateid(), target);
  }

  // uint64 lastLogIndex = 3;
  if (this->_internal_lastlogindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_lastlogindex(), target);
  }

  // uint64 lastLogTerm = 4;
  if (this->_internal_lastlogterm() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_lastlogterm(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Raft.RequestVote.Request)
  return target;
}

::size_t RequestVote_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Raft.RequestVote.Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_term());
  }

  // uint64 candidateId = 2;
  if (this->_internal_candidateid() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_candidateid());
  }

  // uint64 lastLogIndex = 3;
  if (this->_internal_lastlogindex() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_lastlogindex());
  }

  // uint64 lastLogTerm = 4;
  if (this->_internal_lastlogterm() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_lastlogterm());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestVote_Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestVote_Request*>(&to_msg);
  auto& from = static_cast<const RequestVote_Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Raft.RequestVote.Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_term() != 0) {
    _this->_impl_.term_ = from._impl_.term_;
  }
  if (from._internal_candidateid() != 0) {
    _this->_impl_.candidateid_ = from._impl_.candidateid_;
  }
  if (from._internal_lastlogindex() != 0) {
    _this->_impl_.lastlogindex_ = from._impl_.lastlogindex_;
  }
  if (from._internal_lastlogterm() != 0) {
    _this->_impl_.lastlogterm_ = from._impl_.lastlogterm_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestVote_Request::CopyFrom(const RequestVote_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Raft.RequestVote.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestVote_Request::IsInitialized() const {
  return true;
}

void RequestVote_Request::InternalSwap(RequestVote_Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.lastlogterm_)
      + sizeof(RequestVote_Request::_impl_.lastlogterm_)
      - PROTOBUF_FIELD_OFFSET(RequestVote_Request, _impl_.term_)>(
          reinterpret_cast<char*>(&_impl_.term_),
          reinterpret_cast<char*>(&other->_impl_.term_));
}

::google::protobuf::Metadata RequestVote_Request::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[4]);
}
// ===================================================================

class RequestVote_Response::_Internal {
 public:
};

RequestVote_Response::RequestVote_Response(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Raft.RequestVote.Response)
}
RequestVote_Response::RequestVote_Response(
    ::google::protobuf::Arena* arena, const RequestVote_Response& from)
    : RequestVote_Response(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE RequestVote_Response::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void RequestVote_Response::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, term_),
           0,
           offsetof(Impl_, votegranted_) -
               offsetof(Impl_, term_) +
               sizeof(Impl_::votegranted_));
}
RequestVote_Response::~RequestVote_Response() {
  // @@protoc_insertion_point(destructor:Raft.RequestVote.Response)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestVote_Response::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestVote_Response::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_._cached_size_),
              false,
          },
          &RequestVote_Response::MergeImpl,
          &RequestVote_Response::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void RequestVote_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:Raft.RequestVote.Response)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.term_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.votegranted_) -
      reinterpret_cast<char*>(&_impl_.term_)) + sizeof(_impl_.votegranted_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestVote_Response::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RequestVote_Response::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestVote_Response_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Raft::RequestVote_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool voteGranted = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RequestVote_Response, _impl_.votegranted_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.votegranted_)}},
    // uint64 term = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(RequestVote_Response, _impl_.term_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.term_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 term = 1;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.term_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // bool voteGranted = 2;
    {PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.votegranted_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RequestVote_Response::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Raft.RequestVote.Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_term(), target);
  }

  // bool voteGranted = 2;
  if (this->_internal_votegranted() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_votegranted(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Raft.RequestVote.Response)
  return target;
}

::size_t RequestVote_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Raft.RequestVote.Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 term = 1;
  if (this->_internal_term() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_term());
  }

  // bool voteGranted = 2;
  if (this->_internal_votegranted() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestVote_Response::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestVote_Response*>(&to_msg);
  auto& from = static_cast<const RequestVote_Response&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Raft.RequestVote.Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_term() != 0) {
    _this->_impl_.term_ = from._impl_.term_;
  }
  if (from._internal_votegranted() != 0) {
    _this->_impl_.votegranted_ = from._impl_.votegranted_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestVote_Response::CopyFrom(const RequestVote_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Raft.RequestVote.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestVote_Response::IsInitialized() const {
  return true;
}

void RequestVote_Response::InternalSwap(RequestVote_Response* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.votegranted_)
      + sizeof(RequestVote_Response::_impl_.votegranted_)
      - PROTOBUF_FIELD_OFFSET(RequestVote_Response, _impl_.term_)>(
          reinterpret_cast<char*>(&_impl_.term_),
          reinterpret_cast<char*>(&other->_impl_.term_));
}

::google::protobuf::Metadata RequestVote_Response::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[5]);
}
// ===================================================================

class RequestVote::_Internal {
 public:
};

RequestVote::RequestVote(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:Raft.RequestVote)
}
RequestVote::RequestVote(
    ::google::protobuf::Arena* arena,
    const RequestVote& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  RequestVote* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Raft.RequestVote)
}









::google::protobuf::Metadata RequestVote::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_server_2eproto_getter,
                                   &descriptor_table_server_2eproto_once,
                                   file_level_metadata_server_2eproto[6]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Raft
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_server_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
