# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/CatchUp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/CatchUp.proto\"\x1e\n\x0bNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\"\x1c\n\x0cNodeResponse\x12\x0c\n\x04node\x18\x01 \x01(\x0c\x32\x38\n\nNodeSender\x12*\n\tsend_node\x12\x0c.NodeRequest\x1a\r.NodeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.CatchUp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEREQUEST']._serialized_start=23
  _globals['_NODEREQUEST']._serialized_end=53
  _globals['_NODERESPONSE']._serialized_start=55
  _globals['_NODERESPONSE']._serialized_end=83
  _globals['_NODESENDER']._serialized_start=85
  _globals['_NODESENDER']._serialized_end=141
# @@protoc_insertion_point(module_scope)
