# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/Client.proto\"\x0f\n\rEmptyResponse\".\n\x08Response\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t26\n\x0eHotStuffClient\x12$\n\x05reply\x12\t.Response\x1a\x0e.EmptyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.Client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYRESPONSE']._serialized_start=22
  _globals['_EMPTYRESPONSE']._serialized_end=37
  _globals['_RESPONSE']._serialized_start=39
  _globals['_RESPONSE']._serialized_end=85
  _globals['_HOTSTUFFCLIENT']._serialized_start=87
  _globals['_HOTSTUFFCLIENT']._serialized_end=141
# @@protoc_insertion_point(module_scope)
