# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/HotStuff.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18src/proto/HotStuff.proto\x12\x08HotStuff\"-\n\x0b\x45\x63hoRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"-\n\x0b\x42\x65\x61tRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\"\x0e\n\x0c\x42\x65\x61tResponse2\x83\x01\n\x0fHotStuffReplica\x12\x37\n\x04\x45\x63ho\x12\x15.HotStuff.EchoRequest\x1a\x16.HotStuff.EchoResponse\"\x00\x12\x37\n\x04\x42\x65\x61t\x12\x15.HotStuff.BeatRequest\x1a\x16.HotStuff.BeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.HotStuff_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ECHOREQUEST']._serialized_start=38
  _globals['_ECHOREQUEST']._serialized_end=83
  _globals['_ECHORESPONSE']._serialized_start=85
  _globals['_ECHORESPONSE']._serialized_end=112
  _globals['_BEATREQUEST']._serialized_start=114
  _globals['_BEATREQUEST']._serialized_end=159
  _globals['_BEATRESPONSE']._serialized_start=161
  _globals['_BEATRESPONSE']._serialized_end=175
  _globals['_HOTSTUFFREPLICA']._serialized_start=178
  _globals['_HOTSTUFFREPLICA']._serialized_end=309
# @@protoc_insertion_point(module_scope)
